import requests
import feedparser
import re
from datetime import datetime
import os

AI_KEYWORDS_EN = ['ai', 'llm', 'gpt', 'claude', 'anthropic', 'openai', 'gemini',
                  'machine learning', 'neural', 'deep learning', 'diffusion',
                  'transformer', 'inference', 'agent', 'rag']

AI_KEYWORDS_ZH = ['ai', '人工智能', '大模型', '语言模型', '机器学习', '深度学习',
                  'llm', 'gpt', 'claude', '智能体', '生成式', 'aigc', '算法',
                  '神经网络', '自动驾驶', 'agent', '多模态']

def fetch_hackernews_ai(limit=6):
    try:
        top_ids = requests.get(
            'https://hacker-news.firebaseio.com/v0/topstories.json', timeout=10
        ).json()[:100]
        stories = []
        for sid in top_ids:
            if len(stories) >= limit:
                break
            s = requests.get(
                f'https://hacker-news.firebaseio.com/v0/item/{sid}.json', timeout=5
            ).json()
            title = s.get('title', '').lower()
            if any(kw in title for kw in AI_KEYWORDS_EN):
                stories.append({
                    'title': s.get('title'),
                    'url': s.get('url') or f'https://news.ycombinator.com/item?id={sid}',
                    'score': s.get('score', 0),
                    'comments': s.get('descendants', 0),
                })
        return stories
    except Exception as e:
        print(f'HN fetch error: {e}')
        return []

def fetch_feed(url, limit=5):
    try:
        feed = feedparser.parse(url)
        results = []
        for entry in feed.entries[:limit]:
            results.append({
                'title': entry.get('title', '').strip(),
                'url': entry.get('link', ''),
            })
        return results
    except Exception as e:
        print(f'Feed fetch error ({url}): {e}')
        return []

def fetch_cn_ai(limit=6):
    """从少数派和爱范儿抓取 AI 相关中文文章"""
    sources = [
        ('少数派', 'https://sspai.com/feed'),
        ('爱范儿', 'https://www.ifanr.com/feed'),
    ]
    results = []
    for source_name, url in sources:
        if len(results) >= limit:
            break
        try:
            feed = feedparser.parse(url)
            for entry in feed.entries:
                if len(results) >= limit:
                    break
                title = entry.get('title', '').lower()
                if any(kw in title for kw in AI_KEYWORDS_ZH):
                    results.append({
                        'title': entry.get('title', '').strip(),
                        'url': entry.get('link', ''),
                        'source': source_name,
                    })
        except Exception as e:
            print(f'CN feed error ({source_name}): {e}')
    return results

def fetch_arxiv_ai(limit=4):
    try:
        feed = feedparser.parse('https://export.arxiv.org/rss/cs.AI')
        papers = []
        for entry in feed.entries[:limit]:
            summary = entry.get('summary', '')
            summary = re.sub(r'<[^>]+>', '', summary)
            summary = summary[:150].strip() + '...'
            papers.append({
                'title': entry.get('title', '').strip(),
                'url': entry.get('link', ''),
                'summary': summary,
            })
        return papers
    except Exception as e:
        print(f'arXiv fetch error: {e}')
        return []

COVER = "https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=1200&auto=format&fit=crop"

def section(title, items, with_summary=False, show_source=False):
    if not items:
        return f'\n## {title}\n\n> 今日暂无内容\n'
    lines = [f'\n## {title}\n']
    for item in items:
        line = f'- [{item["title"]}]({item["url"]})'
        if 'score' in item:
            line += f' · ⭐{item["score"]} 💬{item["comments"]}'
        if show_source and item.get('source'):
            line += f' `{item["source"]}`'
        lines.append(line)
        if with_summary and item.get('summary'):
            lines.append(f'  > {item["summary"]}')
    return '\n'.join(lines) + '\n'

def build_cn_post(date_str, date_full, cn):
    return f"""---
title: "AI 中文社区日报 · {date_str}"
date: {date_full}
lastmod: {date_full}
author: liaoshihang
cover: {COVER}
categories:
  - AI 动态
tags:
  - AI
  - 日报
  - 中文
draft: false
---

每日中文 AI 资讯，来源：少数派 · 爱范儿。

<!--more-->
{section('少数派 · 爱范儿', cn, show_source=True)}
---

*由 GitHub Actions 自动生成 · {date_str}*
"""

def build_en_post(date_str, date_full, hn, verge, arxiv):
    return f"""---
title: "AI Global Daily · {date_str}"
date: {date_full}
lastmod: {date_full}
author: liaoshihang
cover: {COVER}
categories:
  - AI 动态
tags:
  - AI
  - 日报
  - English
draft: false
---

Daily AI news from Hacker News · The Verge · arXiv.

<!--more-->
{section('Hacker News · AI 热议', hn)}
{section('The Verge · AI News', verge)}
{section('arXiv · Latest Papers', arxiv, with_summary=True)}
---

*Auto-generated by GitHub Actions · {date_str}*
"""

def send_discord(webhook_url, date_str, cn_count, en_count, site_url):
    try:
        requests.post(webhook_url, json={
            'embeds': [
                {
                    'title': f'🇨🇳 AI 中文日报 {date_str}',
                    'description': f'收录 **{cn_count}** 条中文资讯',
                    'url': f'{site_url}/posts/ai-news-cn-{date_str}/',
                    'color': 0xE74C3C,
                    'footer': {'text': 'DrGoose · 少数派 · 爱范儿'}
                },
                {
                    'title': f'🌍 AI Global Daily {date_str}',
                    'description': f'收录 **{en_count}** 条英文资讯',
                    'url': f'{site_url}/posts/ai-news-en-{date_str}/',
                    'color': 0x5865F2,
                    'footer': {'text': 'DrGoose · HN · The Verge · arXiv'}
                },
            ]
        }, timeout=10)
    except Exception as e:
        print(f'Discord notify error: {e}')

if __name__ == '__main__':
    now = datetime.now()
    date_str = now.strftime('%Y-%m-%d')
    date_full = now.strftime('%Y-%m-%dT09:00:00+08:00')

    print('Fetching HN...')
    hn = fetch_hackernews_ai()
    print(f'  {len(hn)} stories')

    print('Fetching The Verge...')
    verge = fetch_feed('https://www.theverge.com/rss/ai-artificial-intelligence/index.xml')
    print(f'  {len(verge)} articles')

    print('Fetching Chinese AI news...')
    cn = fetch_cn_ai()
    print(f'  {len(cn)} articles')

    print('Fetching arXiv...')
    arxiv = fetch_arxiv_ai()
    print(f'  {len(arxiv)} papers')

    os.makedirs('content/posts', exist_ok=True)

    cn_path = f'content/posts/ai-news-cn-{date_str}.md'
    with open(cn_path, 'w', encoding='utf-8') as f:
        f.write(build_cn_post(date_str, date_full, cn))
    print(f'Written: {cn_path}')

    en_path = f'content/posts/ai-news-en-{date_str}.md'
    with open(en_path, 'w', encoding='utf-8') as f:
        f.write(build_en_post(date_str, date_full, hn, verge, arxiv))
    print(f'Written: {en_path}')

    webhook = os.environ.get('DISCORD_WEBHOOK')
    site = os.environ.get('SITE_URL', 'https://liaoshihang.com')
    if webhook:
        send_discord(webhook, date_str, len(cn), len(hn) + len(verge) + len(arxiv), site)
        print('Discord notified.')
    else:
        print('No DISCORD_WEBHOOK set, skipping notification.')
